// Auto-generated by scripts/export_to_arduino.py — DO NOT EDIT
// Source  : training/models/scaler_params_2s.npz
// Features: 12
//   ax_s1, ay_s1, az_s1, gx_s1, gy_s1, gz_s1, ax_s2, ay_s2, az_s2, gx_s2, gy_s2, gz_s2
#pragma once

// Z-score: normalized = (x - SCALER_MEAN[i]) / (SCALER_STD[i] + 1e-8)
const float SCALER_MEAN[12] = {-0.68434000f, -0.00894887f, -0.09006628f, 0.93435675f, -0.70402551f, 4.09880495f, -0.05330881f, 0.13045426f, -0.06323719f, -1.19057202f, -0.85108322f, 2.05429816f};
const float SCALER_STD[12] = {0.56136942f, 0.58023393f, 0.35396072f, 48.06306076f, 67.36008453f, 64.95095825f, 0.61441457f, 0.98234314f, 0.27810001f, 42.27396774f, 48.39131927f, 119.49255371f};
