// Auto-generated by FusionGait training pipeline — DO NOT EDIT
// Source: scaler_params_2s.npz
// Features (12): ax_s1, ay_s1, az_s1, gx_s1, gy_s1, gz_s1, ax_s2, ay_s2, az_s2, gx_s2, gy_s2, gz_s2
#pragma once

// Z-score: norm[i] = (x[i] - SCALER_MEAN[i]) / (SCALER_STD[i] + 1e-8f)
const float SCALER_MEAN[12] = {-0.65186560f, -0.04610360f, -0.06855708f, -0.00482519f, 5.68227482f, 8.69822693f, -0.04544911f, 0.44082969f, -0.08485016f, -3.84597754f, 0.81496114f, 6.27282524f};
const float SCALER_STD[12] = {0.58233917f, 0.57619059f, 0.32267267f, 46.59333801f, 65.29571533f, 70.08410645f, 0.60426533f, 0.85876161f, 0.25457242f, 44.32632828f, 48.99222946f, 118.34111023f};
