#!/usr/bin/env python3
"""
export_to_arduino.py — Exporta artefactos del notebook al firmware del Master.

    python3 scripts/export_to_arduino.py            # auto-detecta N_SENSORS
    python3 scripts/export_to_arduino.py --sensors 3

Qué hace:
  1. Copia training/models/gait_model_Xs.h  → firmware/inference_master/gait_model.h
  2. Lee  training/models/scaler_params_Xs.npz
     → genera firmware/inference_master/scaler.h
  3. Verifica que N_FEATURES del scaler coincide con N_SLAVES en config.h
"""
import sys, re, argparse, pathlib
import numpy as np

ROOT         = pathlib.Path(__file__).parent.parent
MODELS_DIR   = ROOT / "training" / "models"
FIRMWARE_DIR = ROOT / "firmware" / "inference_master"
CONFIG_H     = FIRMWARE_DIR / "config.h"


def read_n_slaves():
    if not CONFIG_H.exists():
        return None
    m = re.search(r"#define\s+N_SLAVES\s+(\d+)", CONFIG_H.read_text())
    return int(m.group(1)) if m else None


def copy_model(n_sensors):
    src = MODELS_DIR / f"gait_model_{n_sensors}s.h"
    if not src.exists():
        candidates = sorted(MODELS_DIR.glob("gait_model_*.h"))
        if not candidates:
            print(f"ERROR: gait_model_{n_sensors}s.h no encontrado. Ejecuta el notebook."); return False
        src = candidates[-1]
        print(f"  (fallback: {src.name})")
    dst = FIRMWARE_DIR / "gait_model.h"
    dst.write_bytes(src.read_bytes())
    print(f"+ Modelo   : {dst.relative_to(ROOT)}  ({src.stat().st_size/1024:.1f} KB  <- {src.name})")
    return True


def gen_scaler(n_sensors):
    npz = MODELS_DIR / f"scaler_params_{n_sensors}s.npz"
    if not npz.exists():
        candidates = sorted(MODELS_DIR.glob("scaler_params_*.npz"))
        if not candidates:
            print(f"ERROR: scaler_params_{n_sensors}s.npz no encontrado. Ejecuta el notebook."); return False
        npz = candidates[-1]
        print(f"  (fallback: {npz.name})")
    data  = np.load(npz)
    mean  = data["mean"].astype("float32")
    std   = data["std"].astype("float32")
    feats = list(data.get("feature_cols", [f"f{i}" for i in range(len(mean))]))
    def arr(a, name):
        return f"const float {name}[{len(a)}] = {{{', '.join(f'{v:.8f}f' for v in a)}}};"
    lines = [
        "// Auto-generated by scripts/export_to_arduino.py — DO NOT EDIT",
        f"// Source  : {npz.relative_to(ROOT)}",
        f"// Features: {len(feats)}  {', '.join(feats)}",
        "#pragma once", "",
        arr(mean, "SCALER_MEAN"),
        arr(std,  "SCALER_STD"), "",
    ]
    (FIRMWARE_DIR / "scaler.h").write_text("\n".join(lines))
    print(f"+ Scaler   : firmware/inference_master/scaler.h  ({len(mean)} features)")
    n_slaves = read_n_slaves()
    expected = 6 * (1 + n_slaves) if n_slaves is not None else None
    if expected and expected != len(mean):
        print(f"\nWARN: scaler={len(mean)} features pero config.h N_SLAVES={n_slaves} -> espera {expected}.")
        print(f"      Ajusta N_SLAVES a {len(mean)//6 - 1} en firmware/inference_master/config.h")
    else:
        print(f"  N_FEATURES={len(mean)} OK (N_SLAVES={n_slaves})")
    return True


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--sensors", type=int, default=None, help="Total sensores (1 master + N slaves)")
    args = ap.parse_args()
    FIRMWARE_DIR.mkdir(parents=True, exist_ok=True)
    n_sensors = args.sensors or (1 + (read_n_slaves() or 1))
    print(f"=== FusionGait export: {n_sensors} sensores (1 master + {n_sensors-1} slave(s)) ===\n")
    ok = copy_model(n_sensors) and gen_scaler(n_sensors)
    if ok:
        print("\nSiguientes pasos:")
        print(f"  1. Sube inference_slave (config.h)     al Arduino 2 (GaitSlave_2)")
        if n_sensors > 2:
            print(f"  2. Sube inference_slave (config_s3.h)  al Arduino 3 (GaitSlave_3)")
        print(f"  {n_sensors}. Sube inference_master al Arduino 1")
        print(f"  {n_sensors+1}. python3 inference/inference_gui.py")
    else:
        sys.exit(1)

if __name__ == "__main__":
    main()
