#!/usr/bin/env python3
"""
export_to_arduino.py — Exporta artefactos del notebook al firmware del Master.

    python3 scripts/export_to_arduino.py

Qué hace:
  1. Convierte training/models/gait_cnn2d_residual_int8.tflite
       → firmware/inference_master/gait_model.h   (array uint8 listo para C)
  2. Lee  training/models/scaler_params_2s.npz
       → firmware/inference_master/scaler.h        (SCALER_MEAN[], SCALER_STD[])
  3. Verifica que N_FEATURES del scaler coincida con N_SLAVES de config.h
  4. Imprime pasos detallados para flashear los dos Arduinos
"""
import sys, re, pathlib
import numpy as np

ROOT         = pathlib.Path(__file__).parent.parent
MODELS_DIR   = ROOT / "training" / "models"
FIRMWARE_DIR = ROOT / "firmware" / "inference_master"
CONFIG_H     = FIRMWARE_DIR / "config.h"

# Modelo preferido (primero disponible de la lista)
MODEL_PRIORITY = [
    "gait_cnn2d_residual_int8.tflite",
    "gait_2s_int8.tflite",
]


def read_n_slaves() -> int | None:
    if not CONFIG_H.exists():
        return None
    m = re.search(r"#define\s+N_SLAVES\s+(\d+)", CONFIG_H.read_text())
    return int(m.group(1)) if m else None


def tflite_to_c_header(tflite_path: pathlib.Path, dst: pathlib.Path) -> bool:
    """Convierte .tflite binario → array uint8 en C (formato xxd -i)."""
    data = tflite_path.read_bytes()
    lines = [
        "// Auto-generated by scripts/export_to_arduino.py",
        f"// Source : {tflite_path.relative_to(ROOT)}",
        f"// Size   : {len(data):,} bytes  ({len(data)/1024:.1f} KB)",
        "// DO NOT EDIT — regenerar: python3 scripts/export_to_arduino.py",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "alignas(8) const uint8_t gait_model[] = {",
    ]
    for i in range(0, len(data), 12):
        chunk = data[i:i+12]
        lines.append("  " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines.append("};")
    lines.append(f"const unsigned int gait_model_len = {len(data)};")
    dst.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"  ✅  {dst.relative_to(ROOT)}  ({len(data)/1024:.1f} KB  ← {tflite_path.name})")
    return True


def gen_scaler(n_sensors: int) -> bool:
    """Lee scaler_params_Xs.npz → genera scaler.h."""
    npz = MODELS_DIR / f"scaler_params_{n_sensors}s.npz"
    if not npz.exists():
        candidates = sorted(MODELS_DIR.glob("scaler_params_*.npz"))
        if not candidates:
            print("  ❌  scaler_params_*.npz no encontrado — ejecuta el notebook.")
            return False
        npz = candidates[-1]
        print(f"  (fallback: {npz.name})")

    data  = np.load(npz)
    mean  = data["mean"].astype("float32")
    std   = data["std"].astype("float32")
    feats = list(data.get("feature_cols", [f"f{i}" for i in range(len(mean))]))

    def arr(a, name):
        return f"const float {name}[{len(a)}] = {{{', '.join(f'{v:.8f}f' for v in a)}}};"

    lines = [
        "// Auto-generated by scripts/export_to_arduino.py — DO NOT EDIT",
        f"// Source  : {npz.relative_to(ROOT)}",
        f"// Features: {len(feats)}",
        f"//   {', '.join(feats)}",
        "#pragma once",
        "",
        "// Z-score: normalized = (x - SCALER_MEAN[i]) / (SCALER_STD[i] + 1e-8)",
        arr(mean, "SCALER_MEAN"),
        arr(std,  "SCALER_STD"),
        "",
    ]
    dst = FIRMWARE_DIR / "scaler.h"
    dst.write_text("\n".join(lines), encoding="utf-8")

    n_slaves = read_n_slaves()
    expected = 6 * (1 + n_slaves) if n_slaves is not None else None
    if expected and expected != len(mean):
        print(f"  ⚠️   {dst.relative_to(ROOT)}  ({len(mean)} features)")
        print(f"       WARN: scaler={len(mean)} features pero N_SLAVES={n_slaves} "
              f"espera {expected} features.")
        print(f"       Ajusta N_SLAVES={len(mean)//6 - 1} en config.h")
        return False

    print(f"  ✅  {dst.relative_to(ROOT)}  ({len(mean)} features — N_SLAVES={n_slaves} OK)")
    return True


def main():
    n_slaves  = read_n_slaves() or 1
    n_sensors = 1 + n_slaves
    FIRMWARE_DIR.mkdir(parents=True, exist_ok=True)

    print(f"\n=== FusionGait export: {n_sensors} sensores "
          f"(master pierna + {n_slaves} slave tobillo) ===\n")

    # ── 1. Modelo ──────────────────────────────────────────────────────────
    model_src = next((MODELS_DIR / n for n in MODEL_PRIORITY
                      if (MODELS_DIR / n).exists()), None)
    if model_src is None:
        print("  ❌  No se encontró ningún .tflite — ejecuta el notebook.")
        sys.exit(1)
    tflite_to_c_header(model_src, FIRMWARE_DIR / "gait_model.h")

    # ── 2. Scaler ──────────────────────────────────────────────────────────
    ok = gen_scaler(n_sensors)
    if not ok:
        sys.exit(1)

    # ── 3. Instrucciones ───────────────────────────────────────────────────
    print()
    print("=" * 62)
    print("PASOS PARA FLASHEAR LOS DOS ARDUINOS")
    print("=" * 62)
    print()
    print("── PASO 1 · Arduino SLAVE → tobillo ────────────────────────")
    print("   a) Copia config_s3.h como config.h para este sketch:")
    print("      cp firmware/inference_slave/config_s3.h \\")
    print("         firmware/inference_slave/config.h")
    print("   b) Abre: firmware/inference_slave/inference_slave.ino")
    print("   c) Board: Arduino Nano 33 BLE Sense | Librería: ArduinoBLE")
    print("   d) SUBE al Arduino del TOBILLO")
    print("   e) LED azul fijo → anunciando como 'GaitSlave_3'")
    print()
    print("── PASO 2 · Arduino MASTER → pierna ────────────────────────")
    print("   a) Abre: firmware/inference_master/inference_master.ino")
    print("   b) Librerías necesarias:")
    print("      - ArduinoBLE")
    print("      - Arduino_TensorFlowLite  (o TensorFlowLite_ESP32)")
    print("      - Arduino_BMI270_BMM150   (Rev2) o Arduino_LSM9DS1")
    print("   c) SUBE al Arduino de la PIERNA")
    print("   d) Abre Monitor Serie @ 115200 baud")
    print()
    print("── PASO 3 · Verificar salida serie del Master ───────────────")
    print("   STATUS:SCANNING GaitSlave_3")
    print("   STATUS:SLAVE_CONNECTED GaitSlave_3")
    print("   STATUS:ALL_SLAVES_CONNECTED")
    print("   ARENA:<bytes>                  ← < 65536 es OK")
    print("   INPUT_SHAPE:(1,50,12,1)        ← debe ser exactamente esto")
    print("   INFER,swing,0.02,0.04,0.03,0.91")
    print()
    print("── LEDs del Master ──────────────────────────────────────────")
    print("   Rojo parpadea  → buscando esclavo BLE")
    print("   Azul fijo      → esclavo conectado, buffer llenándose")
    print("   Verde fijo     → inferencia activa")
    print()
    print("── Visualización en PC ──────────────────────────────────────")
    print("   python3 inference/inference_gui.py")
    print()
    print("── Archivos generados ───────────────────────────────────────")
    print("   firmware/inference_master/gait_model.h  ← modelo int8")
    print("   firmware/inference_master/scaler.h      ← normalización")
    print()


if __name__ == "__main__":
    main()
